name: mvp-3.5 CICD + Security Pipelines

on:
 push:
  branches: ["main"]

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Set up Docker
    uses: docker/setup-buildx-action@v2

  - name: Build Docker image
    run: docker build -t mvp-3 .

  - name: Run Trivy security scan
    run: |
      sudo apt-get update
      sudo apt-get install wget -y
      wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.48.0_Linux-64bit.deb
      sudo dpkg -i trivy_0.48.0_Linux-64bit.deb
      trivy image mvp-3
